// Code generated by goctl. DO NOT EDIT.
package types

type ChangePasswordRequest struct {
	OldPassword string `json:"old_password" validate:"required,max=30"`
	NewPassword string `json:"new_password" validate:"required,max=30"`
}

type CreateCategoryRequest struct {
	CategoryName string `json:"category_name" validate:"omitempty,max=50"`
	Color        string `json:"color" validate:"omitempty,max=50"`
}

type CreatePromptRequest struct {
	PromptName string `json:"prompt_name" validate:"max=50"`
	Content    string `json:"content" validate:"max=10240"`
}

type DeletePromptRequest struct {
	PromptID uint `json:"prompt_id" validate:"omitempty,min=1"`
}

type LoginRequest struct {
	Email    string `json:"email" validate:"required,max=50,email"`
	Password string `json:"password" validate:"required,max=30,min=6"`
}

type LoginResponse struct {
	UserId    uint   `json:"user_id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	Avatar    string `json:"avatar"`
	Token     string `json:"token"`
	ExpiredAt int64  `json:"expire_at"`
}

type RefreshTokenResponse struct {
	Token     string `json:"token"`
	ExpiredAt int64  `json:"expire_at"`
}

type RegisterUserRequest struct {
	Name     string `json:"name" validate:"max=50"`
	Password string `json:"password" validate:"min=6"`
	Email    string `json:"email" validate:"email,max=80"`
}

type UpdatePromptRequest struct {
	PromptID   uint   `json:"prompt_id" validate:"omitempty,min=1"`
	PromptName string `json:"prompt_name" validate:"max=50"`
	Content    string `json:"content" validate:"max=10240"`
}

type UpdateUserRequest struct {
	UserID uint   `json:"user_id" validate:"omitempty,min=1"`
	Name   string `json:"name,optional" validate:"omitempty,max=50"`
	Avatar string `json:"avatar" validate:"omitempty,max=300"`
	Email  string `json:"email" validate:"omitempty,email,max=100"`
}
