// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCategoryTable = "category_table"

// CategoryTable mapped from table <category_table>
type CategoryTable struct {
	ID             int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CategoryName   string         `gorm:"column:category_name;not null" json:"category_name"`
	Color          string         `gorm:"column:color;not null" json:"color"`
	CategoryStatus int32          `gorm:"column:category_status;default:1" json:"category_status"`
	Description    string         `gorm:"column:description" json:"description"`
	CreatedBy      string         `gorm:"column:created_by;not null" json:"created_by"`
	CreatedAt      time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName CategoryTable's table name
func (*CategoryTable) TableName() string {
	return TableNameCategoryTable
}
