// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePromptsCountTable = "prompts_count_table"

// PromptsCountTable mapped from table <prompts_count_table>
type PromptsCountTable struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PromptsID   int32          `gorm:"column:prompts_id;not null" json:"prompts_id"`
	LikeCount   int32          `gorm:"column:like_count;not null" json:"like_count"`
	ReviewCount int32          `gorm:"column:review_count;not null" json:"review_count"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName PromptsCountTable's table name
func (*PromptsCountTable) TableName() string {
	return TableNamePromptsCountTable
}
