// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUsersTokenTable = "users_token_table"

// UsersTokenTable mapped from table <users_token_table>
type UsersTokenTable struct {
	ID             int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID         int32          `gorm:"column:user_id" json:"user_id"`
	PreEfreshToken string         `gorm:"column:pre_efresh_token" json:"pre_efresh_token"`
	RefreshToken   string         `gorm:"column:refresh_token;not null" json:"refresh_token"`
	CreatedAt      time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UsersTokenTable's table name
func (*UsersTokenTable) TableName() string {
	return TableNameUsersTokenTable
}
