// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUsersTable = "users_table"

// UsersTable mapped from table <users_table>
type UsersTable struct {
	ID          int32          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserName    string         `gorm:"column:user_name;not null" json:"user_name"`
	Password    string         `gorm:"column:password;not null" json:"password"`
	Email       string         `gorm:"column:email;not null" json:"email"`
	UserStatus  int32          `gorm:"column:user_status;default:1" json:"user_status"`
	Avatar      string         `gorm:"column:avatar" json:"avatar"`
	Description string         `gorm:"column:description" json:"description"`
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
}

// TableName UsersTable's table name
func (*UsersTable) TableName() string {
	return TableNameUsersTable
}
