# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: install-tools
        shell: bash
        run: |-
          set -eEu
          set +o pipefail
          ls -la
          make install-tools

      - name: go-lint
        shell: bash
        run: |-
          set -eEu
          set +o pipefail
          make lint

      - name: Build
        env:
          ALIYUNCS_REGISTRY_PASSWD: ${{ secrets.ALIYUNCS_REGISTRY_PASSWD }}
          ALIYUNCS_REGISTRY_USER: ${{ secrets.ALIYUNCS_REGISTRY_USER }}
        run: pwd && ls && ./build.sh 0.0.1
